<a href="https://colab.research.google.com/github/xuhu357/DataAnalysis/blob/master/ch07_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A4%80%EB%B9%84%ED%95%98%EA%B8%B0_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 개별화와 양자화

연속성 데이터는 종종 개별로 분할하거나, 분석을 위해 그룹별로 나누기도 함.

수업에 참여하는 학생 데이터가 있고, 나이대에 따라 분류한다고 가정

In [0]:
import pandas as pd
import numpy as np

In [0]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

### 하고 싶은 것:
* 18-25, 26-35, 36-60, 60 이상으로 나누어 보기.

#### 실습

In [0]:
bins = [18, 25, 35, 60, 100]

cats = pd.cut(ages, bins)

In [4]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

pandas에서 반환하는 객체는 Categorical 객체라고 하는 특수한 객체인데,

이 객체는 그룹이름이 담긴 배열이라고 생각하면 된다.

Categorical 객체는 codes속성에 있는 ages 데이터에 대한 카테고리 이름을 categories라는 배열에 내부적으로 잠고 있다. 

In [5]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [6]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [7]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

보다싶이 괄호로 시작해서 대괄호로 끝나는것은 왼쪽부분은 미포함, 오른쪽은 포함이라는 뜻, 
why, closed= right 이기 때문에.

위치를 바꾸고 싶다면, 
right =False를 넘기면 끝.

In [8]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

### 나누어진 그룹에게 이름을 주고 싶다면, 어떻게 할까?

#### 실습

In [9]:
group_names = ['Youth', 'YouthAdult', 'MiddleAged', 'Senior']

pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YouthAdult, Youth, ..., YouthAdult, Senior, MiddleAged, MiddleAged, YouthAdult]
Length: 12
Categories (4, object): [Youth < YouthAdult < MiddleAged < Senior]

만약, cut 함수에 명시적으로 경계값을 주지 않고 그룹의 개수를 넘겨주면, 데이터에서 최소값과 최대값을 기준으로 균등한 길이의 그룹을 자동으로 계산한다. 

In [10]:
# 실습

data = np.random.rand(20)

pd.cut(data, 4, precision=2)

[(0.47, 0.69], (0.69, 0.91], (0.69, 0.91], (0.69, 0.91], (0.24, 0.47], ..., (0.24, 0.47], (0.02, 0.24], (0.02, 0.24], (0.69, 0.91], (0.69, 0.91]]
Length: 20
Categories (4, interval[float64]): [(0.02, 0.24] < (0.24, 0.47] < (0.47, 0.69] < (0.69, 0.91]]

이를 위한 가장 적합한 함수로, qcut가 있다. 

이는 표본 변위치를 기반으로 데이터를 나눠준다.

cut함수를 사용하게 되면, 데이터의 분산에 따라 각각의 그룹마다 데이터의 개수가 다르게 나누어지는 경우가 많다. 

qcut은 표준 변위치를 사용하기 때문에 적당히 같은 크기의 그룹으로 나눌 수 있다. 

In [11]:
temp_cats = pd.cut(data, 4, precision=2)

pd.value_counts(temp_cats)

(0.69, 0.91]    7
(0.24, 0.47]    5
(0.02, 0.24]    5
(0.47, 0.69]    3
dtype: int64

In [12]:
qcut_cats = pd.qcut(data, 4)

pd.value_counts(qcut_cats) # cut into quartiles.

(0.771, 0.911]     5
(0.492, 0.771]     5
(0.269, 0.492]     5
(0.0194, 0.269]    5
dtype: int64

cut함수와 유사하게 변위치를 직접 지정해줄 수 있다. 변위치 값은 0부터 1까지.

In [13]:
qcut_cats2 = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

pd.value_counts(qcut_cats2)

(0.492, 0.783]     8
(0.167, 0.492]     8
(0.783, 0.911]     2
(0.0194, 0.167]    2
dtype: int64

In [14]:
qcut_cats2

[(0.492, 0.783], (0.783, 0.911], (0.492, 0.783], (0.492, 0.783], (0.167, 0.492], ..., (0.167, 0.492], (0.0194, 0.167], (0.167, 0.492], (0.492, 0.783], (0.492, 0.783]]
Length: 20
Categories (4, interval[float64]): [(0.0194, 0.167] < (0.167, 0.492] < (0.492, 0.783] < (0.783, 0.911]]

그룹 분석과 변위치를 다룰때는 cut과 qcutㅎ마수 같은 이산함수가 특히 유용.

이 내용은 수집과 그룹연산에 대한 chapter에서 더 자세히 보자.

### 특이값 찾아내고 제외하기.


배열 연산을 수행할 때는 특이값 outlier를 제외하거나 적당한 값으로 대체하는 것이 중요하다. 


In [0]:
np.random.seed(12345)

data = pd.DataFrame(np.random.randn(1000, 4))

In [16]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

이 DataFrame의 한 칼럼에서 절대값이 3을 초과하는 값을 찾아내자.

#### 실습

In [0]:
col = data[3]

In [18]:
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

### 절대값이 3을 초과 하는 모든 로우를 선택하려면 어떻게 해야 할까?

#### 실습

In [20]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

이 기준으로 쉽게 값을 선택할 수 있으며, 아래 코드로 -3이나, 3을 초과하는 값을 -3 혹은 3으로 지정할 있다.

In [0]:
data[(np.abs(data) > 3)] = np.sign(data) * 3

In [22]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

유니버설 함수인ㄴ np.sign()은 주어진 값이 부호에 따라 1이거나 -1인 배열을 반환.

### 치환과 임의 샘플링

numpy.random.permutation함수를 이용하면, Series나 DataFrame의 로우를 쉬베 임의의 순서대로 재배치 가능.

순서를 바꾸고 싶은 만큼의 길이를 permutation함수에 넘기면, 바뀐 순서가 담김 정수 배열이 생성.

In [0]:
df = pd.DataFrame(np.arange(20).reshape(5, 4))

In [24]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [0]:
sampler = np.random.permutation(5)

In [26]:
sampler

array([1, 0, 2, 3, 4])

이렇게 생성된 배열은 ix기반의 색인이나, take함수에 사용 가능.

In [27]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

치환없이 일부만 임의로 선택하려면, permutation함수의 반환된 배열에서 원하는 크기 k 만큼만 처음부터 잘라내면 된다. 

치환하지 않고 표본을 수집하는 효과적인 알고리즘도 많지만, 이 방법은 손쉽게 사용 가능.

In [28]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

치환을 통해 표본을 생성하기 위한 가장 빠른 방법은 randint를 통해서 생성한 난수를 이용하는 방법이다.

In [0]:
bag = np.array([5, 7, -1, 6, 4])

sampler = np.random.randint(0, len(bag), size=10)

In [30]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [0]:
draws = bag.take(sampler)

In [32]:
draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

오늘은 여기까지 2019.3.15